"""empty message

Revision ID: 102c387b1649
Revises: 
Create Date: 2024-12-09 11:12:42.212528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102c387b1649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('animal_type', sa.String(), nullable=False),
    sa.Column('personality', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
